from pyspark.sql.types import StructField, StructType, StringType, IntegerType

source_api_schema = StructType([
    StructField("date", IntegerType(), True),
    StructField("state", StringType(), True),
    StructField("positive", IntegerType(), True),
    StructField("probable_cases", IntegerType(), True),
    StructField("negative", IntegerType(), True),
    StructField("pending", IntegerType(), True),
    StructField("totalTestResultsSource", StringType(), True),
    StructField("totalTestResults", IntegerType(), True),
    StructField("hospitalizedCurrently", IntegerType(), True),
    StructField("hospitalizedCumulative", IntegerType(), True),
    StructField("inIcuCurrently", IntegerType(), True),
    StructField("inIcuCumulative", IntegerType(), True),
    StructField("onVentilatorCurrently", IntegerType(), True),
    StructField("onVentilatorCumulative", IntegerType(), True),
    StructField("recovered", IntegerType(), True),
    StructField("lastUpdateEt", StringType(), True),
    StructField("dateModified", StringType(), True),
    StructField("checkTimeEt", StringType(), True),
    StructField("death", IntegerType(), True),
    StructField("hospitalized", IntegerType(), True),
    StructField("hospitalizedDischarged", IntegerType(), True),
    StructField("dateChecked", StringType(), True),
    StructField("totalTestsViral", IntegerType(), True),
    StructField("positiveTestsViral", IntegerType(), True),
    StructField("negativeTestsViral", IntegerType(), True),
    StructField("positiveCasesViral", IntegerType(), True),
    StructField("deathConfirmed", IntegerType(), True),
    StructField("deathProbable", IntegerType(), True),
    StructField("totalTestEncountersViral", IntegerType(), True),
    StructField("totalTestsPeopleViral", IntegerType(), True),
    StructField("totalTestsAntibody", IntegerType(), True),
    StructField("positiveTestsAntibody", IntegerType(), True),
    StructField("negativeTestsAntibody", IntegerType(), True),
    StructField("totalTestsPeopleAntibody", IntegerType(), True),
    StructField("positiveTestsPeopleAntibody", IntegerType(), True),
    StructField("negativeTestsPeopleAntibody", IntegerType(), True),
    StructField("totalTestsPeopleAntigen", IntegerType(), True),
    StructField("positiveTestsPeopleAntigen", IntegerType(), True),
    StructField("totalTestsAntigen", IntegerType(), True),
    StructField("positiveTestsAntigen", IntegerType(), True),
    StructField("fips", StringType(), True),
    StructField("positiveIncrease", IntegerType(), True),
    StructField("negativeIncrease", IntegerType(), True),
    StructField("total", IntegerType(), True),
    StructField("totalTestResultsIncrease", IntegerType(), True),
    StructField("posNeg", IntegerType(), True),
    StructField("dataQualityGrade", StringType(), True),
    StructField("deathIncrease", IntegerType(), True),
    StructField("hospitalizedIncrease", IntegerType(), True),
    StructField("hash", StringType(), True),
    StructField("commercialScore", IntegerType(), True),
    StructField("negativeRegularScore", IntegerType(), True),
    StructField("negativeScore", IntegerType(), True),
    StructField("positiveScore", IntegerType(), True),
    StructField("score", IntegerType(), True),
    StructField("grade", StringType(), True)
])

mysql_schema = [
    'date',
    'state',
    'positive',
    'probable_cases',
    'negative',
    'pending',
    'total_test_results_source',
    'total_test_results',
    'hospitalized_currently',
    'hospitalized_cumulative',
    'in_icu_currently',
    'in_icu_cumulative',
    'on_ventilator_currently',
    'on_ventilator_cumulative',
    'recovered',
    'last_update_et',
    'date_modified',
    'check_time_et',
    'death',
    'hospitalized',
    'hospitalized_discharged',
    'date_checked',
    'total_tests_viral',
    'positive_tests_viral',
    'negative_tests_viral',
    'positive_cases_viral',
    'death_confirmed',
    'death_probable',
    'total_test_encounters_viral',
    'total_tests_people_viral',
    'total_tests_antibody',
    'positive_tests_antibody',
    'negative_tests_antibody',
    'total_tests_people_antibody',
    'positive_tests_people_antibody',
    'negative_tests_people_antibody',
    'total_tests_people_antigen',
    'positive_tests_people_antigen',
    'total_tests_antigen',
    'positive_tests_antigen',
    'fips',
    'positive_increase',
    'negative_increase',
    'total',
    'total_test_results_increase',
    'pos_neg',
    'data_quality_grade',
    'death_increase',
    'hospitalized_increase',
    'hash',
    'commercial_score',
    'negative_regular_score',
    'negative_score',
    'positive_score',
    'score',
    'grade'
]
